# Generated by Django 3.2.5 on 2021-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210929_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
    ]
