# Generated by Django 3.2.5 on 2021-09-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210929_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name='Дата поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(blank=True, null=True, verbose_name='Время поста'),
        ),
    ]
